### ISSUE TITLE
Cannot find libmkl_intel_lp64.so

### ISSUE THREAD

**Issue by rubenvereecken** [pymc-devs/pymc2#113]
Here goes the full error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ruben/anaconda/lib/python2.7/site-packages/pymc/__init__.py", line 30, in <module>
    from .CommonDeterministics import *
  File "/home/ruben/anaconda/lib/python2.7/site-packages/pymc/CommonDeterministics.py", line 21, in <module>
    from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
  File "/home/ruben/anaconda/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

It's straightforward. I know what it wants. I just can't find that library anywhere and it does not seem to be installed. Can you point me where I can find it or explain what it is?

**Comment by fonnesbeck** [comment]
Cannot reproduce here. Closing. Please reopen with additional details if this is still a problem.
