### ISSUE TITLE
Error when using Poisson to fill in missing values

### ISSUE THREAD

**Issue by Kirubaharan** [pymc-devs/pymc2#12]
I am getting the following error, when I tried to use Poission to fill in the missing values:
The code is in this link: https://github.com/Kirubaharan/hydrology/blob/master/weather_had.py

Traceback (most recent call last):
  File "/home/kiruba/PycharmProjects/area_of_curve/hydrology/weather_had.py", line 128, in <module>
    wind_speed = pm.Poisson('wind_speed', mu=rate, value=masked_values, observed=True)
  File "/home/kiruba/.local/lib/python2.7/site-packages/pymc/distributions.py", line 318, in **init**
    **arg_dict_out)
  File "/home/kiruba/.local/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 772, in **init**
    if not isinstance(self.logp, float):
  File "/home/kiruba/.local/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 929, in get_logp
    raise ZeroProbability(self.errmsg)
pymc.Node.ZeroProbability: Stochastic wind_speed's value is outside its support,
 or it forbids its parents' current values.

**Comment by fonnesbeck** [comment]
This is a model mis-specification issue, not a bug. It means that the initial parameter value for the likelhood are incompatible with the data -- you need to specify compatible initial values.

The best place to get help with this is on [StackOverflow](http://stackoverflow.com/questions/tagged/pymc). Create a question and put the `pymc` tag on it.
