### ISSUE TITLE
Strange NameError Issue

### ISSUE THREAD

**Issue by steveehlert** [pymc-devs/pymc2#130]
Hi all-

I am running into a very strange error whose origin I cannot ascertain. I am not sure what is causing it, but here is the error output. Are there any reasons I would expect something like this? I have a good amount of experience running the pymc library and don't know why this would happen now. 

```
Tuning at iteration 1000
Metropolis_massindex tuning:
    value: 1.99308772654
    acceptance rate: 0.035
    adaptive scale factor: 0.5
```

Traceback (most recent call last):
  File "FlareFit.py", line 178, in <module>
    MCMCModel.sample(iter=20000, burn=2000,progress_bar=True,verbose=2)  #We do 12,000 steps in our chain with a burn in of 2000
  File "/usr/local/lib/python2.7/site-packages/pymc/MCMC.py", line 279, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/usr/local/lib/python2.7/site-packages/pymc/Model.py", line 251, in sample
    self._loop()
  File "/usr/local/lib/python2.7/site-packages/pymc/MCMC.py", line 294, in _loop
    self.tune()
  File "/usr/local/lib/python2.7/site-packages/pymc/MCMC.py", line 361, in tune
    '\t\tTuning step method %s, returned %i\n' %i
NameError: global name 'i' is not defined

**Comment by fonnesbeck** [comment]
You appear to have quite an old version of PyMC. Can you try updating to the most recent release, or better yet, install from master:

```
pip install -U git+https://github.com/pymc-devs/pymc.git
```
