### ISSUE TITLE
Problems importing flib

### ISSUE THREAD

**Issue by bocklund** [pymc-devs/pymc2#145]
I've installed pymc using the latest master building with `python setup.py config_fc --fcompiler gfortran build`. I got a host of warnings when compiling, but everything appeared to compile without error. 

- Linux
- Python version is 2.7.12
- gfortran and gcc version are both 4.4.7

Trying to import pymc gives me the following error:

```
>>> import pymc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/04492/bocklund/.virtualenvs/pymc/lib/python2.7/site-packages/pymc/__init__.py", line 29, in <module>
    from .InstantiationDecorators import *
  File "/home1/04492/bocklund/.virtualenvs/pymc/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 28, in <module>
    from .utils import get_signature
  File "/home1/04492/bocklund/.virtualenvs/pymc/lib/python2.7/site-packages/pymc/utils.py", line 14, in <module>
    from . import flib
ImportError: /home1/04492/bocklund/.virtualenvs/pymc/lib/python2.7/site-packages/pymc/flib.so: undefined symbol: i0_
```

I get the same ImportError when installing from pip, though I have not tried anaconda.

**Comment by bocklund** [comment]
Just tried to build and install numpy without a binary as suggested in #119 and that failed. Closing this for now.
