### ISSUE TITLE
pymc.test() failure in test_plot

### ISSUE THREAD

**Issue by MarcoCast79** [pymc-devs/pymc2#152]
I get the following messages when testing my installation of pymc:

```
> pymc.test()
Running unit tests for pymc.tests
NumPy version 1.11.3
NumPy relaxed strides checking option: False
NumPy is installed in /home/marco/anaconda2/lib/python2.7/site-packages/numpy
Python version 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
.....E.E..../home/marco/anaconda2/lib/python2.7/site-packages/pymc/Node.py:403: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.__name__ = input['__name__']
/home/marco/anaconda2/lib/python2.7/site-packages/pymc/Node.py:403: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.__name__ = input['__name__']
.................................S.......................................................................................................0            x
1    (x_pow_2)
dtype: object
.....SS....................[-----------------100%-----------------] 1000 of 1000 complete in 0.3 sec
.[-----------------100%-----------------] 1000 of 1000 complete in 0.1 sec
...............
======================================================================
ERROR: test_plot (pymc.tests.test_MCMCSampler.test_MCMC)
----------------------------------------------------------------------

>Traceback (most recent call last):
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/tests/test_MCMCSampler.py", line 66, in test_plot
>    plot(self.M.early_mean, path=DIR, verbose=0)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/Matplot.py", line 360, in wrapper
>    f(data, name, *args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/Matplot.py", line 462, in plot
>    savefig("%s%s%s.%s" % (path, name, suffix, format))
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py">, line 697, in savefig
    res = fig.savefig(*args, **kwargs)						>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",> line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)					>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bas>es.py", line 2244, in print_figure
    **kwargs)									>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/ba>ckend_agg.py", line 545, in print_png
    FigureCanvasAgg.draw(self)							>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/ba>ckend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)						>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py",> line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)					>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py",> line 1143, in draw
    renderer, self, dsu, self.suppressComposite)				>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", >line 139, in _draw_list_compositing_images
    a.draw(renderer)								>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py",> line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)					>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.>py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)			>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", >line 139, in _draw_list_compositing_images
    a.draw(renderer)								>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py",> line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)					>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/text.py", l>ine 798, in draw
    mtext=mtext)								>
  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/ba>ckend_agg.py", line 254, in draw_tex
    Z = texmanager.get_grey(s, size, self.dpi)					>
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 588, in get_grey
>    pngfile = self.make_png(tex, fontsize, dpi)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 511, in make_png
>    dvifile = self.make_dvi(tex, fontsize)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 427, in make_dvi
>    report))
>RuntimeError: LaTeX was not able to process the following string:
>''
>Here is the full report generated by LaTeX: 
>
>This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=latex)
> restricted \write18 enabled.
>entering extended mode
>(./61a177676e6ee9185f295d96e21ae57f.tex
>LaTeX2e <2016/02/01>
>Babel <3.9q> and hyphenation patterns for 3 language(s) loaded.
>(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
>Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
>(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
>(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
>(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
>For additional information on amsmath, use the `?' option.
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
>(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
>(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
>
>Package geometry Warning: Over-specification in `h'-direction.
>    `width' (5058.9pt) is ignored.
>
>
>Package geometry Warning: Over-specification in `v'-direction.
>    `height' (5058.9pt) is ignored.
>
>) (./61a177676e6ee9185f295d96e21ae57f.aux)
>(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
>(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)
>*geometry* driver: auto-detecting
>*geometry* detected driver: dvips
>(./61a177676e6ee9185f295d96e21ae57f.aux) )
>No pages of output.
>Transcript written on 61a177676e6ee9185f295d96e21ae57f.log.
>
>
> ======================================================================
> ERROR: test_plot (pymc.tests.test_MCMCSampler.test_tiny_MCMC)
> ----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/tests/test_MCMCSampler.py", line 39, in test_plot
>    plot(self.M, path=DIR, verbose=0)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/Matplot.py", line 341, in wrapper
>    f(data, name, *args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/pymc/Matplot.py", line 462, in plot
>    savefig("%s%s%s.%s" % (path, name, suffix, format))
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
>    res = fig.savefig(*args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1572, in savefig
>    self.canvas.print_figure(*args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2244, in print_figure
>    **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 545, in print_png
>    FigureCanvasAgg.draw(self)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
>    self.figure.draw(self.renderer)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
>    draw(artist, renderer, *args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/figure.py", line 1143, in draw
>    renderer, self, dsu, self.suppressComposite)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
>    a.draw(renderer)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
>    draw(artist, renderer, *args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2409, in draw
>    mimage._draw_list_compositing_images(renderer, self, dsu)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
>    a.draw(renderer)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
>    draw(artist, renderer, *args, **kwargs)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/text.py", line 798, in draw
>    mtext=mtext)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 254, in draw_tex
>    Z = texmanager.get_grey(s, size, self.dpi)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 588, in get_grey
>    pngfile = self.make_png(tex, fontsize, dpi)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 511, in make_png
>    dvifile = self.make_dvi(tex, fontsize)
>  File "/home/marco/anaconda2/lib/python2.7/site-packages/matplotlib/texmanager.py", line 427, in make_dvi
>    report))
>RuntimeError: LaTeX was not able to process the following string:
>''
>Here is the full report generated by LaTeX: 
>
>This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=latex)
> restricted \write18 enabled.
>entering extended mode
>(./61a177676e6ee9185f295d96e21ae57f.tex
>LaTeX2e <2016/02/01>
>Babel <3.9q> and hyphenation patterns for 3 language(s) loaded.
>(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
>Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
>(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
>(/usr/share/texlive/texmf-dist/tex/latex/type1cm/type1cm.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/psnfss/mathptmx.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/base/textcomp.sty
>(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
>For additional information on amsmath, use the `?' option.
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
>(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
>(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
>(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
>(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
>
>Package geometry Warning: Over-specification in `h'-direction.
>    `width' (5058.9pt) is ignored.
>
>
>Package geometry Warning: Over-specification in `v'-direction.
>    `height' (5058.9pt) is ignored.
>
>) (./61a177676e6ee9185f295d96e21ae57f.aux)
>(/usr/share/texlive/texmf-dist/tex/latex/base/ts1cmr.fd)
>(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1ptm.fd)
>*geometry* driver: auto-detecting
>*geometry* detected driver: dvips
>(./61a177676e6ee9185f295d96e21ae57f.aux) )
>No pages of output.
>Transcript written on 61a177676e6ee9185f295d96e21ae57f.log.
>
>
>----------------------------------------------------------------------
>Ran 192 tests in 24.438s
>
>FAILED (SKIP=3, errors=2)
><nose.result.TextTestResult run=192 errors=2 failures=0>
```

Any help? 

Thanks!

**Comment by fonnesbeck** [comment]
These are all LaTeX errors, which I have not seen before. I will try to replicate it here. The good news is it should not affect any results outside of plotting with `Matplot`.
