### ISSUE TITLE
Successfully installed but can't import

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc2#195]
I installed pymc using `pip install pymc --user` and it seemed to be installed normally. 

> Successfully installed pymc-2.3.6 

However, when I import pymc in python shell, I get the follow error message. Not sure how to deal with this. 

> Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import pymc
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/7s2/.local/lib/python3.7/site-packages/pymc/__init__.py", line 19, in <module>
>     from .threadpool import *
>   File "/home/7s2/.local/lib/python3.7/site-packages/pymc/threadpool.py", line 346
>     def await(self):
>             ^
> SyntaxError: invalid syntax

**Comment by pilemendoza** [comment]
I am having the same issue. It worked a couple days ago and now when I running the same code I get """---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-26-e46b348a9125> in <module>
----> 1 import pymc as pm

~/anaconda3/lib/python3.8/site-packages/pymc/__init__.py in <module>
     27 from .Container import *
     28 from .PyMCObjects import *
---> 29 from .InstantiationDecorators import *
     30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *

~/anaconda3/lib/python3.8/site-packages/pymc/InstantiationDecorators.py in <module>
     26 from .Container import Container
     27 import numpy as np
---> 28 from .utils import get_signature
     29 
     30 special_methods_available = [True]

~/anaconda3/lib/python3.8/site-packages/pymc/utils.py in <module>
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: numpy.core.multiarray failed to import

"""
Updated Numpy and used  import numpy.core.multiarray ....
