### ISSUE TITLE
AssertionError:  Arrays are not almost equal to 7 decimals

### ISSUE THREAD

**Issue by charles-crawford** [pymc-devs/pymc2#41]
# 
## ERROR: test_stats_after_reload (pymc.tests.test_MCMCSampler.test_MCMC)

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/pymc/tests/test_MCMCSampler.py", line 81, in test_stats_after_reload
    db = database.pickle.load('MCMC.pickle')
  File "/Applications/anaconda/lib/python2.7/site-packages/pymc/database/pickle.py", line 82, in load
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: 'MCMC.pickle'
# 
## FAIL: test_nonsep (pymc.tests.test_basiscov.test_basiscov)

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/pymc/tests/test_basiscov.py", line 82, in test_nonsep
    assert_almost_equal(C2(xstack), C(xstack))
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(mismatch 100.0%)
 x: array([[ 21.7581876,  21.7581876,  21.7581876, ...,  21.7581876,
         21.7581876,  21.7581876],
       [ 21.7581876,  21.7581876,  21.7581876, ...,  21.7581876,...
 y: array([[ 21.3644798,  21.4933572,  21.5826082, ...,  21.5826082,
         21.4933572,  21.3644798],

**Comment by fonnesbeck** [comment]
What is your setup? I'm not getting this on OS X using PyMC built from source.

**Comment by charles-crawford** [comment]
Good afternoon,

Thanks for getting back to me. This error occurred on a Linux machine. But I installed pymc on my mac and got a similar error after the "FAIL: test_nonsep (pymc.tests.test_basiscov.test_basiscov)" line.

I installed both using the anaconda command "conda install".

**Comment by charles-crawford** [comment]
# Here is the error I get on my Mac:

## FAIL: test_gradients (pymc.tests.test_gradients.test_gradients)

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/pymc/tests/test_gradients.py", line 345, in test_gradients
    check_gradients(chi2)
  File "/Applications/anaconda/lib/python2.7/site-packages/pymc/tests/test_gradients.py", line 147, in check_gradients
    " is not correct.")
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/Applications/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 3 decimals
analytic gradient for chi2 with respect to parameter chi2 is not correct.
(mismatch 20.0%)
 x: array([ -1.312e+00,  -2.958e+00,  -3.816e-01,  -3.356e-01,  -3.485e+06])
 y: array([ -1.312e+00,  -2.958e+00,  -3.816e-01,  -3.356e-01,  -3.492e+06])

---

Ran 179 tests in 18.911s

FAILED (SKIP=2, failures=1)
Out[2]: <nose.result.TextTestResult run=179 errors=0 failures=1>

**Comment by fonnesbeck** [comment]
Any idea which Fortran compiler you have?

Can you try installing from source?

```
pip install -U git+git://github.com/pymc-devs/pymc.git
```

**Comment by charles-crawford** [comment]
Ok, I installed with pip like you said, and it looks like the test was completed. I did get a couple of deprecation warnings, though. Do you think this will cause me problems in the future?

............/Applications/anaconda/lib/python2.7/site-packages/pymc/Node.py:403: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.**name** = input['**name**']
/Applications/anaconda/lib/python2.7/site-packages/pymc/Node.py:403: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.**name** = input['**name**']
...........S.............S.......................................................................................................0            x
1    (x_pow_2)
dtype: object

##  [-----------------100%-----------------] 1000 of 1000 complete in 0.1 sec............

Ran 180 tests in 26.018s

OK (SKIP=2)

**Comment by fonnesbeck** [comment]
Nothing that I am aware of. You should be good.

**Comment by charles-crawford** [comment]
Awesome! Thanks for the help! I'm looking forward to diving in!
