### ISSUE TITLE
issue with the hdf5 backend

### ISSUE THREAD

**Issue by jac2130** [pymc-devs/pymc2#56]
I'm having an issue with the hdf5 backend; it won't write the chains to file and here is the error message.  I'd greatly appreciate help on this issue! 

```
/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py:996: PerformanceWarning:
table      ``/chain0/PyMCsamples`` is exceeding the recommended maximum number of columns   
 (512); be ready to see PyTables asking for *lots* of memory and possibly slow I/O PerformanceWarning)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/var/www/blog/ExperimentResults.py", line 1736, in <module>
  S.sample(iter=100000, burn=10000, thin = 10)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pymc/MCMC.py", line 277, in sample
  Sampler.sample(self, iter, length, verbose)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pymc/Model.py", line 243, in sample
  self.db._initialize(self._funs_to_tally, length)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/pymc/database/hdf5.py", line 444, in  _initialize
  expectedrows=length)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/file.py", line 1060, in create_table
  chunkshape=chunkshape, byteorder=byteorder)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 871, in __init__
  byteorder, _log)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/leaf.py", line 262, in __init__
  super(Leaf, self).__init__(parentnode, name, _log)
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/node.py", line 270, in __init__
self._v_objectid = self._g_create()
File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tables/table.py", line 1023, in _g_create
self._v_new_title, self.filters.complib or '', obversion)
File "tables/tableextension.pyx", line 212, in tables.tableextension.Table._create_table  (tables/tableextension.c:3080)
tables.exceptions.HDF5ExtError: Problems creating the table
```

**Comment by fonnesbeck** [comment]
As the message suggests at the top, it looks like you are exceeding the number of columns that PyTables is meant to be working with. I assume this means you have a lot of variables (or variables with a large number of elements). Try to avoid saving the traces of variables you won't need (i.e. intermediate values) using the `trace=False` argument on those nodes.

**Comment by jac2130** [comment]
Thank you, I'll do that.

**Comment by jac2130** [comment]
Is there any way at all, then, to deal with large data sets (say millions of rows with missing values etc.) and stream traces of many parameter models to disk?

**Comment by fonnesbeck** [comment]
Sorry for the late reply. MCMC is not an ideal method of inference for very large data. For most sampling methods the data likelihood has to be evaluated at every iteration, so it becomes highly inefficient. That said, we could probably use some innovation for handling very large output; this innovation will likely take place in PyMC3 rather than here.
